#ifndef _UANT_CC_H_
#define _UANT_CC_H_

typedef enum {
    UANT_NOOP_CC,
    UANT_RESET_COUNTERS_CC,
    UANT_RESET_APP_CMD_COUNTERS_CC,
    UANT_RESET_DEVICE_CMD_COUNTERS_CC,
    UANT_DEVICE_INIT_CC,

    UANT_RESET_CC,
    UANT_GET_DEPLOYMENT_STATUS_CC,
    UANT_ARM_ANTENNA_SYSTEMS_CC,
    UANT_DISARM_CC,
    UANT_AUTOMATED_DEPLOYMENT_CC,
    UANT_CANCEL_DEPLOYMENT_ACTIVATION_CC,

    UANT_DEPLOY_ANT1_CC,
    UANT_DEPLOY_ANT2_CC,
    UANT_DEPLOY_ANT3_CC,
    UANT_DEPLOY_ANT4_CC,
    UANT_DEPLOY_ANT1_OVERRIDE_CC,
    UANT_DEPLOY_ANT2_OVERRIDE_CC,
    UANT_DEPLOY_ANT3_OVERRIDE_CC,
    UANT_DEPLOY_ANT4_OVERRIDE_CC,
    UANT_REPORT_ANT_ACTIVATION_CNT_CC,
    UANT_REPORT_ANT_ACTIVATION_TIME_CC,
    UANT_MEASURE_SYSTEM_TEMPERATURE_CC,
}uant_cc_n;

#endif