#ifndef _COSMIC_PERFIDS_H_
#define _COSMIC_PERFIDS_H_

typedef enum {
    COSMIC_OFFSET_PERFID      = 80,
    IFC_PERF_ID,
    FM_PERF_ID,
    EPS_PERF_ID,
    ADCS_PERF_ID,
    GRX_PERF_ID,
    STX_PERF_ID,
    UANT_PERF_ID,
    UTRX_PERF_ID,
    PAYC_PERF_ID,
    PAYR_PERF_ID,
    PAYS_PERF_ID,
    CI_PERF_ID,
    CT_PERF_ID,
    TO_MAIN_TASK_PERF_ID,
    TO_APP_TASK_PERF_ID,
    TO_SUB_TASK_PERF_ID,
    SN_PERF_ID,
    HK_PERF_ID,
    SCH_PERF_ID,
    DS_PERF_ID,
    LOG_PERF_ID,
    
}COSMIC_perfids_n;

#endif